import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({ selector: 'xh-scrutiny-edr-content', standalone: true, templateUrl: './scrutiny-edr-content.component.html', styleUrls: ['./scrutiny-dlp-content.component.css', './scrutiny-edr-content.component.css'], changeDetection: ChangeDetectionStrategy.OnPush })
export class ScrutinyEdrContentComponent {
  readonly capabilities = [
    ['Behavioural Detection','Self-learning analytics identify suspicious behaviour instead of relying on signatures alone.'],['Real-Time Monitoring','Continuous visibility into processes, files, registry and network connections.'],['Threat Investigation','Timeline, process tree and MITRE ATT&CK mapping show what actually happened.'],['Threat Hunting','Proactively search for threats across the entire endpoint estate.'],['Response Actions','Isolate a host, kill a process, quarantine a file and remediate remotely.'],['Forensics & Evidence','Preserve evidence for incident response, insurers and audits.'],['Ransomware Protection','Stop ransomware behaviour before encryption damage is done.'],['Lateral Movement Detection','Block unauthorised movement before it reaches critical systems.'],['Credential Theft Prevention','Detect credential abuse and suspicious account access.'],['Fileless Attack Detection','Identify malicious scripts, memory activity and living-off-the-land techniques.'],['Cloud & Identity Context','Correlate endpoint events with cloud and identity signals.'],['Ecosystem Integration','Integrate with SIEM, SOAR and Vortex SOC.']
  ];
  readonly faqs = [
    ['How is this different from the antivirus we already have?','Traditional antivirus matches files to known threats. EDR follows process, registry and network behaviour to find fileless attacks, living-off-the-land techniques and unknown variants, then provides a timeline and process tree.'],['What is the performance impact on an endpoint?','The agent is lightweight and runs in the background. Because impact varies by hardware and installed software, older or specialised estates begin with a representative pilot group.'],['Can it actually stop ransomware, or only report it?','It acts on mass file changes, shadow-copy tampering and encryption behaviour. Analysts can stop the process, isolate the host, quarantine files and remediate remotely with a full audit trail.'],['How long does rollout take?','The agent deploys in waves through your endpoint tooling. Most rollout time goes into the pilot and policy tuning rather than installation.'],['Does it work if a laptop is off the corporate network?','Yes. It keeps enforcing policy and recording telemetry wherever the device is, then synchronises when it reconnects.'],['Do we need our own analysts to use it?','Not necessarily. Your IT team can operate it, or XcellHost’s Mumbai SOC can provide 24×7 monitoring, investigation, response, threat hunting and reporting.']
  ];
  toggleFaq(event: Event): void { (event.currentTarget as HTMLElement).parentElement?.classList.toggle('open'); }
}
