import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'xh-vortex-soc-content',
  standalone: true,
  templateUrl: './vortex-soc-content.component.html',
  styleUrl: './vortex-soc-content.component.css',
  styles: [`
    :host .soc-content { gap: 22px; margin-bottom: 22px; }
    :host .soc-content > section > .pp-sec { margin-bottom: 10px; }
    :host .soc-content .pp-ov { line-height: 1.65; }
    :host .soc-feature-grid { margin-top: 14px; gap: 13px; }
    :host .soc-cap-grid, :host .soc-flow { margin-top: 13px; }
    :host .soc-tags, :host .soc-deploy { margin-top: 12px; }
    :host .soc-note { margin-top: 12px; }
    :host{display:block;min-width:0;width:100%}:host .soc-content,:host .soc-content>section{min-width:0;width:100%}
    :host .soc-feature-grid article{border-color:#d9e7fb;background:linear-gradient(145deg,#fff 42%,#f0f6ff);box-shadow:0 14px 34px -29px #075fd1;transition:.25s ease}:host .soc-feature-grid article:nth-child(2){background:linear-gradient(145deg,#fff 42%,#effbf6)}:host .soc-feature-grid article:nth-child(3){background:linear-gradient(145deg,#fff 42%,#f6f0ff)}:host .soc-feature-grid article:nth-child(4){background:linear-gradient(145deg,#fff 42%,#eefbff)}:host .soc-feature-grid article:hover,:host .soc-cap-grid article:hover{transform:translateY(-3px);box-shadow:0 18px 38px -25px rgba(5,58,130,.5)}
    :host .soc-feature-grid i,:host .soc-cap-grid span{background:linear-gradient(135deg,#176de0,#6840bb);color:#fff;box-shadow:0 8px 18px -9px #2848b8}:host .soc-cap-grid article{position:relative;overflow:hidden;border-color:#dce7f6;background:#fff;box-shadow:0 12px 28px -29px #07396e;transition:.25s ease}:host .soc-cap-grid article:nth-child(3n+2) span{background:linear-gradient(135deg,#049d86,#17bc7d)}:host .soc-cap-grid article:nth-child(3n) span{background:linear-gradient(135deg,#ef8b16,#f4b12a)}
    :host .soc-flow article{border-color:#d5e4f7;background:linear-gradient(180deg,#fff,#f1f7ff)}:host .soc-flow article:nth-child(3){border-color:#89b9f4;background:linear-gradient(145deg,#0b458f,#176de0)}:host .soc-flow article:nth-child(3) :is(i,b,span){color:#fff}:host .soc-flow article:nth-child(3) i{background:rgba(255,255,255,.18)}:host .soc-panes article{border-color:#d9e5f3;box-shadow:0 15px 34px -30px #092b57}:host .soc-panes h3{background:linear-gradient(110deg,#0b326d,#1475df)}:host .soc-panes .green h3{background:linear-gradient(110deg,#087554,#18ad78)}:host .soc-panes .purple h3{background:linear-gradient(110deg,#4d2b9e,#8251dc)}
    :host .soc-mitre{padding:58px 32px;border:0;border-radius:0;background:#fff}:host .soc-kicker{width:max-content;margin:0 auto 14px;padding:7px 17px;border:1px solid #b8d4fb;border-radius:999px;background:#fff;color:#075fd1;font:800 10px var(--mono);letter-spacing:.08em;text-transform:uppercase}:host .soc-mitre>h2{margin:0;color:#071f48;font-size:clamp(27px,3vw,40px);line-height:1.12;text-align:center}:host .soc-mitre-intro{max-width:720px;margin:14px auto 30px;color:#536b8d;line-height:1.65;text-align:center}
    :host .soc-matrix-shell{overflow:hidden;padding:8px;border:1px solid #dce6f3;border-radius:18px;background:#fff;box-shadow:0 22px 50px -38px #061c42}:host .soc-matrix{display:grid;width:100%;grid-template-columns:repeat(12,minmax(0,1fr));gap:6px}:host .soc-tactic{min-width:0;border-radius:9px;background:#f8fafc}:host .soc-tactic header{min-height:91px;padding:9px 7px;border-bottom:1px solid #dde7f3;background:#f0f4f9}:host .soc-tactic header small{color:#637b9b;font:800 7px var(--mono)}:host .soc-tactic header h3{overflow-wrap:anywhere;margin:3px 0;color:#102748;font-size:10.5px;line-height:1.12}:host .soc-tactic header span{color:#7185a0;font-size:7.5px}:host .soc-techniques{display:grid;align-content:start;gap:5px;padding:5px}:host .soc-techniques button{min-width:0;min-height:61px;overflow-wrap:anywhere;padding:7px 6px;border:1px solid #72dfb8;border-radius:7px;background:#dcf8ed;color:#173f37;font:500 8.6px/1.22 var(--body);text-align:left;cursor:pointer;transition:.18s ease}:host .soc-techniques button small{display:block;margin-bottom:3px;color:#08765c;font:700 7px var(--mono)}:host .soc-techniques button.warn{border-color:#f4ca5e;background:#fff4cf;color:#614316}:host .soc-techniques button.high{border-color:#f2a1a1;background:#ffe7e7;color:#6d2626}:host .soc-techniques button:hover,:host .soc-techniques button.active{outline:2px solid #1682ef;outline-offset:0;transform:translateY(-1px);box-shadow:0 8px 16px -12px #075fd1}
    :host .soc-response{display:block;margin-top:18px;padding:28px 32px;border-radius:17px;background:linear-gradient(110deg,#1f6edb,#124b9e);color:#fff;box-shadow:0 18px 38px -28px #0754b4}:host .soc-response span{color:#b9dcff;font:800 9px var(--mono);letter-spacing:.09em;text-transform:uppercase}:host .soc-response h3{margin:10px 0 3px;color:#fff;font-size:22px}:host .soc-response h4{margin:0;color:#62f0bd;font-size:14px}:host .soc-response p{max-width:900px;margin:17px 0 0;color:#fff;font-size:13px;line-height:1.6}
    :host .soc-deploy article{border-color:#d8e6f7;background:linear-gradient(145deg,#fff,#f0f6ff);box-shadow:0 12px 28px -27px #075fd1}:host .soc-deploy article:nth-child(2){background:linear-gradient(145deg,#fff,#effbf6)}:host .soc-deploy article:nth-child(3){background:linear-gradient(145deg,#fff,#f6f0ff)}:host .soc-deploy article:nth-child(4){background:linear-gradient(145deg,#fff,#fff6e6)}:host .soc-tags span{border-color:#c5dbf8;background:#f1f7ff}:host .soc-note{border-radius:0 12px 12px 0;background:linear-gradient(90deg,#edf4ff,#f7f9ff)}
    @media(max-width:1050px){:host .soc-matrix{grid-template-columns:repeat(6,minmax(0,1fr))}}
    @media(max-width:800px){:host .soc-mitre{padding:42px 0}:host .soc-matrix{grid-template-columns:repeat(3,minmax(0,1fr))}}
    @media(max-width:520px){:host .soc-matrix{grid-template-columns:repeat(2,minmax(0,1fr))}:host .soc-response{padding:23px 20px}}
    @media (max-width: 700px) { :host .soc-content { gap: 20px; margin-bottom: 20px; } }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class VortexSocContentComponent {
  readonly attackMatrix = [
    { id: 'TA0001', name: 'Initial Access', techniques: [{id:'T1566.001',name:'Spearphishing Attachment',level:'safe'},{id:'T1566.002',name:'Spearphishing Link',level:'safe'},{id:'T1190',name:'Exploit Public-Facing Application',level:'safe'},{id:'T1133',name:'External Remote Services',level:'safe'},{id:'T1078',name:'Valid Accounts',level:'safe'}] },
    { id: 'TA0002', name: 'Execution', techniques: [{id:'T1059.001',name:'PowerShell',level:'warn'},{id:'T1059',name:'Command and Scripting Interpreter',level:'warn'},{id:'T1203',name:'Exploitation for Client Execution',level:'safe'},{id:'T1047',name:'Windows Management Instrumentation',level:'safe'},{id:'T1053.005',name:'Scheduled Task',level:'safe'}] },
    { id: 'TA0003', name: 'Persistence', techniques: [{id:'T1547.001',name:'Registry Run Keys / Startup Folder',level:'safe'},{id:'T1053',name:'Scheduled Task / Job',level:'safe'},{id:'T1136',name:'Create Account',level:'safe'},{id:'T1098',name:'Account Manipulation',level:'safe'},{id:'T1574',name:'Hijack Execution Flow',level:'safe'}] },
    { id: 'TA0004', name: 'Privilege Escalation', techniques: [{id:'T1068',name:'Exploitation for Privilege Escalation',level:'high'},{id:'T1134',name:'Access Token Manipulation',level:'safe'},{id:'T1548',name:'Abuse Elevation Control Mechanism',level:'safe'},{id:'T1574',name:'Hijack Execution Flow',level:'safe'},{id:'T1055',name:'Process Injection',level:'high'}] },
    { id: 'TA0005', name: 'Defense Evasion', techniques: [{id:'T1027',name:'Obfuscated / Compressed Files',level:'safe'},{id:'T1070',name:'Indicator Removal on Host',level:'safe'},{id:'T1112',name:'Modify Registry',level:'safe'},{id:'T1036',name:'Masquerading',level:'safe'},{id:'T1218',name:'Signed Binary Proxy Execution',level:'safe'}] },
    { id: 'TA0006', name: 'Credential Access', techniques: [{id:'T1003',name:'OS Credential Dumping',level:'high'},{id:'T1555',name:'Credentials from Password Stores',level:'safe'},{id:'T1110',name:'Brute Force',level:'safe'},{id:'T1056',name:'Input Capture',level:'safe'},{id:'T1556',name:'Modify Authentication Process',level:'safe'}] },
    { id: 'TA0007', name: 'Discovery', techniques: [{id:'T1082',name:'System Information Discovery',level:'warn'},{id:'T1083',name:'File and Directory Discovery',level:'warn'},{id:'T1057',name:'Process Discovery',level:'warn'},{id:'T1046',name:'Network Service Discovery',level:'warn'},{id:'T1018',name:'Remote System Discovery',level:'warn'}] },
    { id: 'TA0008', name: 'Lateral Movement', techniques: [{id:'T1021',name:'Remote Services',level:'safe'},{id:'T1570',name:'Lateral Tool Transfer',level:'warn'},{id:'T1550',name:'Use Alternate Authentication Material',level:'safe'},{id:'T1210',name:'Exploitation of Remote Services',level:'safe'},{id:'T1534',name:'Internal Spearphishing',level:'safe'}] },
    { id: 'TA0009', name: 'Collection', techniques: [{id:'T1005',name:'Data from Local System',level:'safe'},{id:'T1113',name:'Screen Capture',level:'safe'},{id:'T1115',name:'Clipboard Data',level:'safe'},{id:'T1560',name:'Archive Collected Data',level:'warn'},{id:'T1074',name:'Data Staged',level:'safe'}] },
    { id: 'TA0011', name: 'Command & Control', techniques: [{id:'T1071',name:'Application Layer Protocol',level:'safe'},{id:'T1095',name:'Non-Application Layer Protocol',level:'safe'},{id:'T1573',name:'Encrypted Channel',level:'safe'},{id:'T1105',name:'Ingress Tool Transfer',level:'safe'},{id:'T1001',name:'Data Obfuscation',level:'safe'}] },
    { id: 'TA0010', name: 'Exfiltration', techniques: [{id:'T1041',name:'Exfiltration Over C2 Channel',level:'high'},{id:'T1048',name:'Exfiltration Over Alternative Protocol',level:'safe'},{id:'T1567',name:'Exfiltration Over Web Service',level:'safe'},{id:'T1020',name:'Automated Exfiltration',level:'safe'},{id:'T1030',name:'Data Transfer Size Limits',level:'safe'}] },
    { id: 'TA0040', name: 'Impact', techniques: [{id:'T1486',name:'Data Encrypted for Impact',level:'high'},{id:'T1490',name:'Inhibit System Recovery',level:'high'},{id:'T1489',name:'Service Stop',level:'safe'},{id:'T1499',name:'Endpoint Denial of Service',level:'safe'},{id:'T1565',name:'Data Manipulation',level:'safe'}] },
  ];
  selectedTechnique = { id: 'T1566.001', name: 'Spearphishing Attachment', tactic: 'Initial Access (TA0001)', summary: 'correlates endpoint, identity, cloud, network, application and log telemetry, raises entity risk, opens a case with evidence, and triggers response actions for containment and reporting.' };
  selectTechnique(tactic: string, technique: {id:string;name:string;level:string}): void {
    const tacticId = this.attackMatrix.find(item => item.name === tactic)?.id ?? '';
    this.selectedTechnique = { id: technique.id, name: technique.name, tactic: `${tactic} (${tacticId})`, summary: 'correlates endpoint, identity, cloud, network, application and log telemetry, raises entity risk, opens a case with evidence, and triggers response actions for containment and reporting.' };
  }
  readonly overview = [
    { icon: 'SIEM', title: 'One data lake, not five consoles', subtitle: 'Every source lands in the same schema', points: ['Endpoint, cloud, network, identity and application telemetry', 'Hot, warm and archive retention', 'Fast search and correlation at scale', 'One query language across every source'] },
    { icon: 'RULE', title: 'Detection you can shape', subtitle: 'A rule library plus a practical builder', points: ['Field, threshold, sequence, anomaly and indicator rules', 'Risk scores, severity and tags', 'MITRE ATT&CK mapping', 'Custom rules without a services engagement'] },
    { icon: 'SOAR', title: 'Response that runs itself', subtitle: 'SOAR is built in', points: ['Drag-and-drop playbooks', 'Automated triage, enrichment and closure', 'Endpoint, network, AD, cloud, email and ITSM actions', 'Human approval gates when required'] },
    { icon: 'LOCAL', title: 'Air-gapped capable', subtitle: 'For environments that cannot touch the internet', points: ['100% on-premise deployment', 'Private cloud inside your tenancy', 'Hybrid across sites and clouds', 'Controlled offline updates'] },
  ];
  readonly capabilities = [
    ['Unified Data Lake SIEM', 'Collect endpoint, cloud, network, application and identity telemetry with tiered retention.'], ['Detection Engineering', 'Build field, threshold, sequence, anomaly and indicator rules with risk and MITRE mapping.'], ['SOAR Playbooks', 'Automate triage, enrichment, assignment, action and closure with approval gates.'], ['UEBA Analytics', 'Baseline user, host and service behaviour, compare peers and score entity risk.'], ['Threat Hunting', 'Search and pivot across endpoint, cloud, network and identity timelines.'], ['Case Management', 'Keep owners, comments, evidence, response history and SLA tracking together.'], ['Cloud Security (CSPM)', 'Continuously check cloud configuration, IAM, networks and storage.'], ['Cloud Native Vulnerability Management', 'Prioritise risks in containers, images, packages, Kubernetes and workloads.'], ['Network Analytics (NBAD)', 'Detect beaconing, lateral movement and exfiltration from traffic metadata.'], ['Endpoint Response Bridge', 'Correlate endpoint alerts and isolate hosts, kill processes, recover files and scan.'], ['Threat Intelligence', 'Enrich IP, domain, hash, URL, certificate and email indicators.'], ['Application Visibility (APM)', 'Correlate traces, logs, metrics and errors with security events.'], ['Dashboards & Reporting', 'Deliver analyst, executive, compliance, SLA, risk and trend views.'], ['Automation Connectors', 'Connect 800+ endpoint, firewall, IAM, cloud, email and ITSM technologies.'], ['Data Governance', 'Apply classification, retention, immutable storage, RBAC and audit logs.'],
  ];
  readonly workflow = [['Alert triage', 'Prioritise by severity, risk and asset criticality'], ['Investigate', 'Correlate activity across every signal source'], ['Respond', 'Run playbooks and containment actions'], ['Document', 'Attach evidence, notes, status and SLA'], ['Close & learn', 'Review the incident and tune rules and playbooks']];
  readonly mitre = ['Initial Access', 'Execution', 'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Credential Access', 'Discovery', 'Lateral Movement', 'Collection', 'Command & Control', 'Exfiltration', 'Impact'];
}
