import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({ selector: 'xh-vortex-soc-content', standalone: true, templateUrl: './vortex-soc-content.component.html', styleUrl: './scrutiny-dlp-content.component.css', changeDetection: ChangeDetectionStrategy.OnPush })
export class VortexSocContentComponent {
  readonly capabilities = [
    ['Unified Data Lake SIEM','Collect endpoint, cloud, network, application and identity telemetry with hot, warm and archive retention.'],['Detection Engineering','Build field-match, threshold, sequence, anomaly and indicator rules with risk scores and MITRE ATT&CK mapping.'],['SOAR Playbooks','Automate triage, enrichment, assignment, action and closure with approval gates where required.'],['UEBA Analytics','Baseline user, host and service behaviour, compare peers and score entity risk.'],['Threat Hunting','Search and pivot across endpoint, cloud, network and identity timelines.'],['Case Management','Keep owners, comments, evidence, response history and SLA tracking together.'],['Cloud Security (CSPM)','Continuously check cloud configuration, IAM, networks and storage with remediation guidance.'],['Cloud Native Vulnerability Management','Discover and prioritise risks in containers, images, packages, Kubernetes and workloads.'],['Network Analytics (NBAD)','Detect beaconing, lateral movement and exfiltration from flow, DNS and traffic metadata.'],['Endpoint Response Bridge','Correlate endpoint alerts and remotely isolate hosts, kill processes, recover files and scan.'],['Threat Intelligence','Enrich IP, domain, hash, URL, certificate and email indicators from multiple sources.'],['Application Visibility (APM)','Correlate application traces, logs, metrics and errors with security events.'],['Dashboards & Reporting','Deliver analyst, engineering, executive, compliance, SLA, risk and trend views.'],['Automation Connectors','Connect 800+ endpoint, firewall, IAM, cloud, email and ITSM technologies.'],['Data Governance','Apply classification, retention, immutable storage, RBAC, audit logs and change tracking.']
  ];
  readonly faqs = [
    ['How is Vortex SOC licensed?','Licensing is scoped to daily ingest, source count, retention and the hot-search window. Tiered hot, warm and archive storage can reduce the cost of long regulatory retention.'],['Can it replace our existing SIEM?','Yes, or it can sit above an existing SIEM as the correlation, automation and case-management layer using connectors, REST APIs and webhooks.'],['What does air-gapped operation involve?','The full stack runs locally without an outbound dependency. Threat intelligence, detections and updates follow a controlled offline process.'],['Do we need a full-time SOC team?','No. A small internal team can use the automation during business hours, or XcellHost’s Mumbai SOC can manage monitoring, investigation and response around the clock.'],['How long does onboarding take?','Onboarding is phased, beginning with high-signal identity, endpoint, firewall and email sources before adding cloud posture, vulnerability, network and application context.'],['What reporting do we get?','Dashboards serve analysts, engineers and executives, with scheduled compliance, SLA, risk, MITRE coverage and trend reports.']
  ];
  toggleFaq(event: Event): void { (event.currentTarget as HTMLElement).parentElement?.classList.toggle('open'); }
}
