import type { LanguageOption } from '../layout/language-picker.component';

export const LANGUAGE_DETAILS: Record<string, Omit<LanguageOption, 'code' | 'name'>> = {
  en: { nativeName: 'English', region: 'International', flag: '🌐' },
  hi: { nativeName: 'हिन्दी', region: 'India', flag: '🇮🇳' },
  mr: { nativeName: 'मराठी', region: 'India', flag: '🇮🇳' },
  ta: { nativeName: 'தமிழ்', region: 'India', flag: '🇮🇳' },
  te: { nativeName: 'తెలుగు', region: 'India', flag: '🇮🇳' },
  gu: { nativeName: 'ગુજરાતી', region: 'India', flag: '🇮🇳' },
  bn: { nativeName: 'বাংলা', region: 'Bangladesh / India', flag: '🇧🇩' },
  kn: { nativeName: 'ಕನ್ನಡ', region: 'India', flag: '🇮🇳' },
  ml: { nativeName: 'മലയാളം', region: 'India', flag: '🇮🇳' },
  pa: { nativeName: 'ਪੰਜਾਬੀ', region: 'India', flag: '🇮🇳' },
  fr: { nativeName: 'Français', region: 'France', flag: '🇫🇷' },
  de: { nativeName: 'Deutsch', region: 'Germany', flag: '🇩🇪' },
  es: { nativeName: 'Español', region: 'Spain', flag: '🇪🇸' },
  pt: { nativeName: 'Português', region: 'Portugal / Brazil', flag: '🇵🇹' },
  it: { nativeName: 'Italiano', region: 'Italy', flag: '🇮🇹' },
  nl: { nativeName: 'Nederlands', region: 'Netherlands', flag: '🇳🇱' },
  ar: { nativeName: 'العربية', region: 'Middle East', flag: '🌐' },
  ur: { nativeName: 'اردو', region: 'Pakistan', flag: '🇵🇰' },
  ru: { nativeName: 'Русский', region: 'Russia', flag: '🇷🇺' },
  ja: { nativeName: '日本語', region: 'Japan', flag: '🇯🇵' },
  ko: { nativeName: '한국어', region: 'South Korea', flag: '🇰🇷' },
  'zh-CN': { nativeName: '中文（简体）', region: 'China', flag: '🇨🇳' },
  'zh-TW': { nativeName: '中文（繁體）', region: 'Taiwan', flag: '🇹🇼' },
  id: { nativeName: 'Bahasa Indonesia', region: 'Indonesia', flag: '🇮🇩' },
  tr: { nativeName: 'Türkçe', region: 'Türkiye', flag: '🇹🇷' },
  vi: { nativeName: 'Tiếng Việt', region: 'Vietnam', flag: '🇻🇳' },
  th: { nativeName: 'ไทย', region: 'Thailand', flag: '🇹🇭' },
};
